name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps

      # Update Snapshots only if the PR body contains '[x] Update Snapshots'
      - name: Update Snapshots if needed
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.body, '[x] Update Snapshots')
        run: yarn test --update-snapshots

      - name: Commit and push updated Snapshots
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.body, '[x] Update Snapshots')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase true 
          git pull origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git add .
          git commit -m "Update Playwright snapshots from Github Action" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}

      - name: Run Playwright tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
